### ISSUE TITLE
Current graph queries could be missing some package versions 

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-data-model#99]
This is what I have noticed on production for few packages, for example `org.wildfly.swarm:odata`:

All analyzed versions for this package (using bookkeeping api):

```
    "analysed_versions": [
      "2012.12.0",
      "2017.12.0",
      "2017.12.1",
      "2018.1.0",
      "2018.2.0",
      "2018.2.0.Final"
      ]
```

Which of these versions are not yet synced to graph ? ( using graph_sync pending API):

```
{
  "data": [
    {
      "ecosystem": "maven",
      "name": "org.wildfly.swarm:odata",
      "version": "2017.12.0"
    }
  ]
}
```

Even after invoking the graph sync API, I still get the pending version as not synced to graph.

```
{
  "data": {
    "count_imported_EPVs": 0,
    "epv": [
      {
        "ecosystem": "maven",
        "name": "org.wildfly.swarm:odata",
        "version": "2017.12.0"
      }
    ],
    "message": "Nothing to be synced to Graph!"
  }
}
```

Notice the message above `"count_imported_EPVs": 0,`. This clearly means that we have atleast one of three issues:

 * Graph queries used to detect if a package is present in graph are incorrect
 * Graph queries used to actually sync this package to graph are incorrect
 * There is some other issue causing this behavior

**Comment by miteshvp** [comment]
> There is some other issue causing this behavior

@tuxdna - acutally the above is correct. I do not see any data in our S3 bucket for the said version of the package. Below is the snapshot for version data

<img width="199" alt="image" src="https://user-images.githubusercontent.com/17736013/36406009-daacad5c-1619-11e8-96e6-46c9352e3d3f.png">
Also, the package level data is in error state.
Maybe you want to try and analyze this package again so that we get the data in S3 and then sync to graph.

**Comment by msrb** [comment]
This issue was moved to openshiftio/openshift.io#2313
